name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - 7.3.5
          - 7.3.4
          - 7.3.3
          - 7.3.2
          - 7.3.1
          - 7.3.0
          - 7.2.2
          - 7.2.1
          - 7.2.0
          - 7.1.3
          - 7.1.2
          - 7.1.1
          - 7.1.0
          - 7.0.1
          - 7.0.0
          - 6.99.14.3
          - 6.99.14.2
          - 6.99.14.1
          - 6.99.14
          - 6.99.13.1
          - 6.99.13
          - 6.99.12.4
          - 6.99.12.3
          - 6.99.12.2
          - 6.99.12.1
          - 6.99.12
          - 6.99.11
          - 6.99.4
          - 6.99.3
          - 6.99.2
          - 6.99.1
          - 6.99.0
          - 6.18.3
          - 6.18.2
          - 6.18.1
          - 6.18.0
          - 6.17.7
          - 6.17.6
          - 6.17.5
          - 6.17.4
          - 6.17.3
          - 6.17.2
          - 6.17.1
          - 6.17.0
          - 6.16.5
          - 6.16.4
          - 6.16.3
          - 6.16.2
          - 6.16.1
          - 6.16.0
          - 6.15.7
          - 6.15.6
          - 6.15.5
          - 6.15.4
          - 6.15.3
          - 6.15.2
          - 6.15.1
          - 6.15.0
          - 6.14.1
          - 6.14.0

    env:
      IMAGE_TAG: docker.pkg.github.com/${{ github.repository }}/renpy:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: docker build . --build-arg RENPY_VERSION=${{ matrix.version }} -t ${{ env.IMAGE_TAG }}

      - name: Test run
        run: docker run -t --rm ${{ env.IMAGE_TAG }} --help

      - name: Publish to GitHub Package Registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker login docker.pkg.github.com -u proudust -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE_TAG }}
